Repository Famailyship-org/api.checkkuleogi.org, pull requests merged in 2024-11, with the labels that each got.

#55 [feature/kkuleogi-28] 오프라인 배치 방식 책 추천 목록 API
  src/main/java/com/Familyship/checkkuleogi/domains/book/dto/BookCachingItem.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/implementation/BookCacheManager.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/implementation/BookManager.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/presentation/BookController.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/service/BookService.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/service/BookServiceImpl.java
  src/main/java/com/Familyship/checkkuleogi/domains/recommend/domain/Recommend.java
Labels: enhancement

#57 [feature/kkuleogi-29] 유저 조회 API, 유저 4-layered 아키텍처 적용
  src/main/java/com/Familyship/checkkuleogi/domains/user/dto/UserDto.java
  src/main/java/com/Familyship/checkkuleogi/domains/user/exception/UserException.java
  src/main/java/com/Familyship/checkkuleogi/domains/user/exception/UserExceptionType.java
  src/main/java/com/Familyship/checkkuleogi/domains/user/implementation/UserManager.java
  src/main/java/com/Familyship/checkkuleogi/domains/user/implementation/mapper/UserDtoMapper.java
  src/main/java/com/Familyship/checkkuleogi/domains/user/presentation/UserController.java
  src/main/java/com/Familyship/checkkuleogi/domains/user/service/UserService.java
  src/main/java/com/Familyship/checkkuleogi/domains/user/service/UserServiceImpl.java
Labels: enhancement, refactoring

#59 [feature/kkuleogi-30] 관리자 북 업데이트 시 캐시 Book 데이터 동기화 (일관성 보장)
  src/main/java/com/Familyship/checkkuleogi/domains/book/implementation/BookAdminManager.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/implementation/BookCacheManager.java
Labels: enhancement, refactoring

#60 [feature/kkuleogi-27] MBTI 히스토리 api 구현
  build.gradle
  src/main/java/com/Familyship/checkkuleogi/config/SecurityConfig.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/domain/repository/ChildMBTILogRepository.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/dto/request/GetChildMbtiLogsRequestDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/dto/response/GetChildMbtiLogsResponseDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/implementation/manager/ChildMbtiManager.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/implementation/mapper/ChildMbtiDtoMapper.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/presentation/ChildController.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/service/ChildService.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/service/ChildServiceImpl.java
Labels: enhancement

#64 [feature/kkuleogi-32] 논리적, 물리적 삭제 및 스프링 배치 적용
  build.gradle
  src/main/java/com/Familyship/checkkuleogi/CheckkuleogiApplication.java
  src/main/java/com/Familyship/checkkuleogi/batchFunc/JobScheduler/CheckActiveUserScheduler.java
  src/main/java/com/Familyship/checkkuleogi/batchFunc/JobScheduler/DeleteHardScheduler.java
  src/main/java/com/Familyship/checkkuleogi/batchFunc/checkActiveUser/CheckActiveUserConfig.java
  src/main/java/com/Familyship/checkkuleogi/batchFunc/deleteMBTIHard/DeleteHardConfig.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/domain/Child.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/domain/ChildMBTI.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/domain/ChildMBTILog.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/domain/repository/ChildMBTILogRepository.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/domain/repository/ChildRepository.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/dto/request/DeleteChildMBTIRequestDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/implementation/InactiveUserBatchJob.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/service/ChildServiceImpl.java
Labels: enhancement

#62 [feature/kkuleogi-31] 관리자 북 삭제 시 캐시 Book 데이터 동기화 (일관성 보장)
  src/main/java/com/Familyship/checkkuleogi/domains/book/implementation/BookAdminManager.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/implementation/BookCacheManager.java
  src/main/java/com/Familyship/checkkuleogi/domains/like/domain/BookLike.java
Labels: bug, enhancement

#66 [feature/kkuleogi-33] 전체 책 목록 조회 API Security 전체 허용 적용
  src/main/java/com/Familyship/checkkuleogi/config/SecurityConfig.java
Labels: enhancement

#68 [feature/kkuleogi-34] aws 배포를 위한 설정 추가
  build.gradle
  compose.yml
  src/main/java/com/Familyship/checkkuleogi/config/SecurityConfig.java
Labels: enhancement
