Repository Famailyship-org/api.checkkuleogi.org, pull requests merged in 2024-10, with the labels that each got.

#2 [feature/kkuleogi-1] 엔티티, 기본 엔티티 구현
  .gitignore
  build.gradle
  src/main/java/com/Familyship/checkkuleogi/domains/book/domain/Book.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/domain/BookMBTI.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/domain/Child.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/domain/ChildMBTI.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/domain/ChildMBTILog.java
  src/main/java/com/Familyship/checkkuleogi/domains/like/domain/BookLike.java
  src/main/java/com/Familyship/checkkuleogi/domains/user/domain/SiteUser.java
  src/main/java/com/Familyship/checkkuleogi/domains/user/domain/enums/Role.java
  src/main/java/com/Familyship/checkkuleogi/global/domain/BaseEntity.java
  src/main/resources/application.yml
Labels: enhancement, good first issue

#5 [feature/kkuleogi-2] 공통, 응답&예외처리 구현
  gradlew
  gradlew.bat
  src/main/java/com/Familyship/checkkuleogi/domains/user/presentation/UserController.java
  src/main/java/com/Familyship/checkkuleogi/global/domain/GlobalControllerAdvice.java
  src/main/java/com/Familyship/checkkuleogi/global/domain/exception/BadRequestException.java
  src/main/java/com/Familyship/checkkuleogi/global/domain/exception/CustomRuntimeException.java
  src/main/java/com/Familyship/checkkuleogi/global/domain/exception/IllegalParameterException.java
  src/main/java/com/Familyship/checkkuleogi/global/domain/exception/NotFoundException.java
  src/main/java/com/Familyship/checkkuleogi/global/domain/response/CommonResponseEntity.java
  src/main/java/com/Familyship/checkkuleogi/global/domain/response/CustomError.java
  src/main/resources/application.yml
Labels: enhancement

#9 [feature/kkuleogi-3] API, 좋아요 API 구현
  src/main/java/com/Familyship/checkkuleogi/domains/book/domain/repository/BookRepository.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/domain/Child.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/domain/repository/ChildRepository.java
  src/main/java/com/Familyship/checkkuleogi/domains/like/domain/BookLike.java
  src/main/java/com/Familyship/checkkuleogi/domains/like/domain/enums/like.txt
  src/main/java/com/Familyship/checkkuleogi/domains/like/domain/repository/BookLikeRepository.java
  src/main/java/com/Familyship/checkkuleogi/domains/like/dto/LikeDto.java
  src/main/java/com/Familyship/checkkuleogi/domains/like/dto/LikeListResponseDto.java
  src/main/java/com/Familyship/checkkuleogi/domains/like/dto/LikeResponseDto.java
  src/main/java/com/Familyship/checkkuleogi/domains/like/exception/DuplicateLikeException.java
  src/main/java/com/Familyship/checkkuleogi/domains/like/presentation/BookLikeController.java
  src/main/java/com/Familyship/checkkuleogi/domains/like/service/BookLikeService.java
  src/main/java/com/Familyship/checkkuleogi/domains/like/service/BookLikeServiceImpl.java
  src/main/java/com/Familyship/checkkuleogi/domains/user/domain/SiteUser.java
Labels: enhancement

#12 [feature/kkuleogi-6] 2차 엔티티 수정
  src/main/java/com/Familyship/checkkuleogi/domains/book/domain/Book.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/domain/BookMBTI.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/domain/Child.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/domain/ChildMBTI.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/domain/ChildMBTILog.java
  src/main/java/com/Familyship/checkkuleogi/domains/like/domain/BookLike.java
  src/main/java/com/Familyship/checkkuleogi/domains/like/dto/LikeDto.java
  src/main/java/com/Familyship/checkkuleogi/domains/like/dto/LikeResponseDto.java
  src/main/java/com/Familyship/checkkuleogi/domains/like/service/BookLikeServiceImpl.java
  src/main/java/com/Familyship/checkkuleogi/domains/user/domain/SiteUser.java
Labels: enhancement

#10 [feature/kkuleogi-4] MBTI API 기능 개발
  src/main/java/com/Familyship/checkkuleogi/domains/child/domain/Child.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/domain/ChildMBTI.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/domain/ChildMBTILog.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/dto/CreateChildRequestDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/dto/CreateChildResponseDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/dto/DeleteChildMBTIRequestDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/dto/ReadChildRequestDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/dto/ReadChildResponseDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/dto/UpdateChildMBTIRequestDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/dto/UpdateChildMBTIResponseDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/infra/ChildMBTILogRepository.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/infra/ChildMBTIRepository.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/infra/ChildRepository.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/presentation/ChildController.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/service/ChildService.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/service/ChildServiceImpl.java
  src/main/java/com/Familyship/checkkuleogi/domains/like/Infra/LikeRepository.java
  src/main/java/com/Familyship/checkkuleogi/domains/like/domain/BookLike.java
Labels: enhancement

#14 [feature/kkuleogi-7] API, 추천책 목록 조회API
  src/main/java/com/Familyship/checkkuleogi/domains/child/domain/ChildMBTI.java
  src/main/java/com/Familyship/checkkuleogi/domains/recommend/domain/Recommend.java
  src/main/java/com/Familyship/checkkuleogi/domains/recommend/domain/enums/enums.txt
  src/main/java/com/Familyship/checkkuleogi/domains/recommend/domain/repository/RecommendRepository.java
  src/main/java/com/Familyship/checkkuleogi/domains/recommend/dto/RecommendResponseDto.java
  src/main/java/com/Familyship/checkkuleogi/domains/recommend/exception/recommend.txt
  src/main/java/com/Familyship/checkkuleogi/domains/recommend/presentation/RecommendController.java
  src/main/java/com/Familyship/checkkuleogi/domains/recommend/service/RecommendService.java
  src/main/java/com/Familyship/checkkuleogi/domains/recommend/service/RecommendServiceImpl.java
Labels: enhancement

#16 [feature/kkuleogi-5] jwt 인증/인가 test api 구현
  build.gradle
  src/main/java/com/Familyship/checkkuleogi/config/SecurityConfig.java
  src/main/java/com/Familyship/checkkuleogi/domains/test/dto/request/Test1RequestDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/test/dto/response/Test1ResponseDto.java
  src/main/java/com/Familyship/checkkuleogi/domains/test/presentation/TestController.java
  src/main/java/com/Familyship/checkkuleogi/domains/test/service/TestService.java
  src/main/java/com/Familyship/checkkuleogi/domains/user/domain/SiteUser.java
  src/main/java/com/Familyship/checkkuleogi/domains/user/domain/repository/UserRepository.java
  src/main/java/com/Familyship/checkkuleogi/domains/user/dto/JwtDto.java
  src/main/java/com/Familyship/checkkuleogi/domains/user/dto/request/CreateUserRequestDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/user/dto/request/LoginUserRequestDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/user/dto/response/CreateUserResponseDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/user/dto/response/LoginUserResponseDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/user/presentation/UserController.java
  src/main/java/com/Familyship/checkkuleogi/domains/user/service/CustomUserDetailsService.java
  src/main/java/com/Familyship/checkkuleogi/domains/user/service/UserService.java
  src/main/java/com/Familyship/checkkuleogi/security/jwt/JwtFilter.java
  src/main/java/com/Familyship/checkkuleogi/security/jwt/JwtProvider.java
  src/main/resources/application.properties
Labels: enhancement

#17 [feature/kkuleogi-8] 책 등록(mbti) API구현 ,OpenAI API부분 사용
  build.gradle
  src/main/java/com/Familyship/checkkuleogi/config/OpenAiConfig.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/domain/Book.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/domain/BookMBTI.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/dto/BookMBTIRequest.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/dto/BookMBTIResponse.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/dto/ChatGPTRequest.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/dto/ChatGPTResponse.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/dto/Message.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/presentation/BookController.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/service/BookService.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/service/BookServiceImpl.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/service/MBTIKeywords.java
Labels: enhancement

#19 [feature/kkuleogi-9] Docker 가상환경 세팅
  .gitignore
  Dockerfile
  compose.yml
  gradlew
Labels: documentation

#25 [feature/kkuleogi-10] 4-Layered Architecture 적용 예시, BookT 도메인 구현
  src/main/java/com/Familyship/checkkuleogi/domains/book/service/BookServiceImpl.java
  src/main/java/com/Familyship/checkkuleogi/domains/like/service/BookLikeServiceImpl.java
  src/main/java/com/Familyship/checkkuleogi/domains/study/business/BookService.java
  src/main/java/com/Familyship/checkkuleogi/domains/study/business/BookServiceImplT.java
  src/main/java/com/Familyship/checkkuleogi/domains/study/domain/BookT.java
  src/main/java/com/Familyship/checkkuleogi/domains/study/domain/enums/BookState.java
  src/main/java/com/Familyship/checkkuleogi/domains/study/dto/request/FeedbackOnBookReq.java
  src/main/java/com/Familyship/checkkuleogi/domains/study/dto/request/ReadBookReq.java
  src/main/java/com/Familyship/checkkuleogi/domains/study/dto/request/RegisterBookReq.java
  src/main/java/com/Familyship/checkkuleogi/domains/study/dto/request/UpdateBookReq.java
  src/main/java/com/Familyship/checkkuleogi/domains/study/dto/response/FeedbackOnBookResp.java
  src/main/java/com/Familyship/checkkuleogi/domains/study/dto/response/ReadBookResp.java
  src/main/java/com/Familyship/checkkuleogi/domains/study/dto/response/RegisterBookResp.java
  src/main/java/com/Familyship/checkkuleogi/domains/study/exception/BookException.java
  src/main/java/com/Familyship/checkkuleogi/domains/study/exception/BookExceptionType.java
  src/main/java/com/Familyship/checkkuleogi/domains/study/exception/ChildException.java
  src/main/java/com/Familyship/checkkuleogi/domains/study/exception/ChildExceptionType.java
  src/main/java/com/Familyship/checkkuleogi/domains/study/implementation/manager/BookManager.java
  src/main/java/com/Familyship/checkkuleogi/domains/study/implementation/manager/ChildManager.java
  src/main/java/com/Familyship/checkkuleogi/domains/study/implementation/mapper/BookDtoMapper.java
  src/main/java/com/Familyship/checkkuleogi/domains/study/implementation/mapper/BookLikeDtoMapper.java
  src/main/java/com/Familyship/checkkuleogi/domains/study/presentation/BookControllerT.java
  src/main/java/com/Familyship/checkkuleogi/domains/study/repository/BookRepositoryT.java
  src/main/java/com/Familyship/checkkuleogi/domains/test/domain/repository/Test.java
  src/main/java/com/Familyship/checkkuleogi/domains/test/domain/repository/TestRepository.java
  src/main/java/com/Familyship/checkkuleogi/domains/test/dto/request/Test1RequestDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/test/dto/response/Test1ResponseDto.java
  src/main/java/com/Familyship/checkkuleogi/domains/test/dto/response/Test2ResponseDto.java
  src/main/java/com/Familyship/checkkuleogi/domains/test/presentation/TestController.java
  src/main/java/com/Familyship/checkkuleogi/domains/test/service/TestService.java
Labels: enhancement, question

#29 [refactoring/kkuleogi-16] 회원 가입 코드 리팩토링, webconfig 추가
  src/main/java/com/Familyship/checkkuleogi/config/SecurityConfig.java
  src/main/java/com/Familyship/checkkuleogi/domains/user/domain/SiteUser.java
  src/main/java/com/Familyship/checkkuleogi/domains/user/dto/request/CreateUserRequestDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/user/service/UserService.java
Labels: bug, refactoring

#33 [feature/kkuleogi-18] 최근 열람 책 목록 조회 API 구현 및 Redis 캐싱
  src/main/java/com/Familyship/checkkuleogi/domains/book/dto/BookCachingItem.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/exception/BookExceptionType.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/implementation/BookCacheManager.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/implementation/BookManager.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/presentation/BookController.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/service/BookService.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/service/BookServiceImpl.java
  src/main/java/com/Familyship/checkkuleogi/domains/like/domain/repository/BookLikeRepository.java
Labels: enhancement, question

#35 [feature/kkuleogi-20] 휴면유저 isActive 분기, 벌크 연산(배치)
  src/main/java/com/Familyship/checkkuleogi/CheckkuleogiApplication.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/implementation/BookCacheManager.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/domain/Child.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/domain/repository/ChildRepository.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/implementation/InactiveUserBatchJob.java
Labels: enhancement, question, test

#38 [feature/kkuleogi-19] API, Book 수정, 삭제 API
  src/main/java/com/Familyship/checkkuleogi/domains/book/dto/request/BookUpdateRequest.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/dto/response/BookResponse.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/implementation/BookAdminManager.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/implementation/GPTManager.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/implementation/mapper/BookDtoMapper.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/presentation/BookController.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/service/BookService.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/service/BookServiceImpl.java
Labels: enhancement

#37 [feature/kkuleogi-21] 유저 토큰으로 자녀 id 반환
  src/main/java/com/Familyship/checkkuleogi/domains/child/domain/repository/ChildRepository.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/dto/LoginChildRequestDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/exception/ChildExceptionType.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/implementation/ChildManager.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/implementation/mapper/ChildDtoMapper.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/presentation/ChildController.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/service/ChildService.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/service/ChildServiceImpl.java
Labels: enhancement

#42 [feature/kkuleogi-24] 자녀 등록 API
  src/main/java/com/Familyship/checkkuleogi/domains/child/domain/Child.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/domain/repository/ChildRepository.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/dto/CreateChildRequestDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/dto/CreateChildRequestMbtiDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/dto/CreateChildResponseDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/dto/CreateChildResponseMbtiDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/implementation/ChildManager.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/implementation/mapper/ChildDtoMapper.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/presentation/ChildController.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/service/ChildService.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/service/ChildServiceImpl.java
  src/main/java/com/Familyship/checkkuleogi/domains/user/domain/SiteUser.java
Labels: enhancement

#44 [feature/kkuleogi-23] 책 조회 API 캐싱 전략 적용 (Redis, Look-aside)
  src/main/java/com/Familyship/checkkuleogi/domains/book/dto/response/BookResponse.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/exception/BookExceptionType.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/implementation/BookCacheManager.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/implementation/BookManager.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/implementation/mapper/BookDtoMapper.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/presentation/BookController.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/service/BookService.java
  src/main/java/com/Familyship/checkkuleogi/domains/book/service/BookServiceImpl.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/implementation/InactiveUserBatchJob.java
  src/main/java/com/Familyship/checkkuleogi/domains/like/domain/enums/like.txt
  src/main/java/com/Familyship/checkkuleogi/domains/like/domain/repository/BookLikeRepository.java
  src/main/java/com/Familyship/checkkuleogi/domains/like/dto/LikeDto.java
  src/main/java/com/Familyship/checkkuleogi/domains/like/dto/LikeListResponseDto.java
  src/main/java/com/Familyship/checkkuleogi/domains/like/dto/LikeResponseDto.java
  src/main/java/com/Familyship/checkkuleogi/domains/like/exception/DuplicateLikeException.java
  src/main/java/com/Familyship/checkkuleogi/domains/like/presentation/BookLikeController.java
  src/main/java/com/Familyship/checkkuleogi/domains/like/service/BookLikeService.java
  src/main/java/com/Familyship/checkkuleogi/domains/like/service/BookLikeServiceImpl.java
Labels: enhancement, help wanted, question

#45 [feature/kkuleogi-24] child id로 정보 조회 API
  src/main/java/com/Familyship/checkkuleogi/domains/child/dto/CreateChildResponseDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/dto/request/CreateChildRequestDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/dto/request/CreateChildRequestMbtiDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/dto/request/DeleteChildMBTIRequestDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/dto/request/LoginChildRequestDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/dto/request/ReadChildRequestDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/dto/request/UpdateChildMBTIRequestDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/dto/response/ChildResponse.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/dto/response/CreateChildResponseDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/dto/response/CreateChildResponseMbtiDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/dto/response/ReadChildResponseDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/dto/response/UpdateChildMBTIResponseDTO.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/implementation/ChildManager.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/implementation/mapper/ChildDtoMapper.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/presentation/ChildController.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/service/ChildService.java
  src/main/java/com/Familyship/checkkuleogi/domains/child/service/ChildServiceImpl.java
Labels: enhancement

#48 [feature/kkuleogi-25] MBTI로직 수정
  src/main/java/com/Familyship/checkkuleogi/domains/child/service/ChildServiceImpl.java
Labels: enhancement, refactoring
